<?php

namespace ReclamationBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($item){
        return $this->createQueryBuilder('R')
            ->andWhere('R.status LIKE :searchitem')
            ->setParameter('searchitem','%'.$item.'%')
            ->getQuery()
            ->execute();
    }

    public function searchByUser($item,$iduser){
        return $this->createQueryBuilder('R')
            ->andWhere('R.status LIKE :searchitem')
            ->andWhere('R.idUser = :idUser')
            ->setParameter('searchitem','%'.$item.'%')
            ->setParameter('idUser',$iduser)
            ->getQuery()
            ->execute();
    }

    public function searchByUserMobile($iduser){
        return $this->createQueryBuilder('R')
            ->andWhere('R.id_user = :id_user')
            ->setParameter('id_user',$iduser)
            ->getQuery()
            ->execute();
    }
}
