reclamation_reclamation:
    resource: "@ReclamationBundle/Controller/ReclamationController.php"
    type:     annotation

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /

livraison:
    resource: "@LivraisonBundle/Resources/config/routing.yml"
    prefix:   /

gp:
    resource: "@GPBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

livr:
    resource: '@LivraisonBundle/Controller/'
    type: annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

api:
    resource: "@LivraisonBundle/Resources/config/routings.yml"
    prefix:   /api

loginMobile:
    path:     /loginMobile/{username}/{password}
    defaults: { _controller: LivraisonBundle:Api:loginMobile }