<?php

namespace LivraisonBundle\Repository;

/**
 * evenementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class evenementsRepository extends \Doctrine\ORM\EntityRepository
{
}
