<?php

namespace LivraisonBundle\Repository;

/**
 * LivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivraisonRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByEtat($role)
{
    $qb = $this->_em->createQueryBuilder('u');
    $qb->select('count(u.id)')
        ->from('LivraisonBundle:Livraison', 'u')
        ->where('u.etat LIKE :roles')
        ->setParameter('roles', '%"'.$role.'"%');

    return $qb->getQuery()->getSingleScalarResult();
}
}
