<?php

namespace LivraisonBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{

    public function findNotification()
{
    $qb = $this->_em->createQueryBuilder();
    $qb->select('u Order BY id DESC LIMIT 3')
        ->from('LivraisonBundle:Notification', 'u');
    return $qb->getQuery()->getResult();
}
}
