<?php

namespace LivraisonBundle\Repository;

/**
 * participantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class participantsRepository extends \Doctrine\ORM\EntityRepository
{
}
